minimumReleaseAgeExclude:
  - '@expo/cli@57.0.24 || 57.0.25 || 57.0.27 || 57.0.28'
  - '@expo/fingerprint@0.20.13'
  - '@expo/prebuild-config@57.0.16 || 57.0.17'
  - expo-asset@57.0.17 || 57.0.19
  - expo-constants@57.0.18 || 57.0.20 || 57.0.21
  - expo-file-system@57.0.7
  - expo-font@57.0.4
  - expo-keep-awake@57.0.2
  - expo-modules-autolinking@57.0.13 || 57.0.14
  - expo-modules-core@57.0.18 || 57.0.19 || 57.0.20 || 57.0.21
  - expo@57.0.22 || 57.0.23 || 57.0.25 || 57.0.26 || 57.0.27
  - '@expo/router-server@57.0.10 || 57.0.11 || 57.0.12'
  - babel-preset-expo@57.0.12 || 57.0.13 || 57.0.14
  - expo-modules-jsi@57.1.1
  - expo-build-properties@57.0.22
  - expo-notifications@57.0.21 || 57.0.22
  - expo-updates@57.0.24 || 57.0.25
  - '@expo/config-plugins@57.0.10'
  - '@expo/config@57.0.10'
  - '@expo/image-utils@0.11.6'
  - '@expo/metro-config@57.0.13'
  - '@expo/metro-file-map@57.0.4'
  - '@expo/require-utils@57.0.6'
  - expo-eas-client@57.0.5
